algoritmo "numero_extenso"
inicio
    inteiro numero

    escreva("Digite um número entre 1 e 5: ")
    leia(numero)

    escolha numero
        caso 1:
            escreva("Um")
        caso 2:
            escreva("Dois")
        caso 3:
            escreva("Três")
        caso 4:
            escreva("Quatro")
        caso 5:
            escreva("Cinco")
        outrocaso:
            escreva("Número inválido")
    fimescolha
fimalgoritmo
